# Generated by Django 4.0.2 on 2022-03-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_registration_ip_routable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
