# Generated by Django 4.0.2 on 2022-03-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_registration_ip_routable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_format_valid',
            field=models.BooleanField(help_text='Designates whether this user has a valid email address.', null=True, verbose_name='email format valid'),
        ),
    ]
